name: CI Build

on: push

env:
  DOTNET_VERSION: 3.1.301

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
#      - name: Test
#        run: dotnet test --no-build -c Release
      - name: Pack
        run: dotnet pack --no-build -c Release -o ../out
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            ./out/*.nupkg
            ./out/*.snupkg
  
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [build]
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Publish package to GitHub
        run: |
          dotnet nuget push *.nupkg --skip-duplicate \
            --api-key "${{secrets.GITHUB_TOKEN}}" \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"